### ISSUE TITLE
Akvo Sites product page:  new layout

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1002]
@samvthom16  would you please start working on the layout/backend of a new Akvo Sites product page for us.  Its in the same tabular style as the RSR product page.

https://www.dropbox.com/s/kbhud9dnvi3hy8n/sites%20page%20mockup%2025-05-2016.pdf?dl=0

If you have any questions while I'm away please contact @Lindaleunissen 
Pay special attention to the spacing between content, rows, etc & also the size of images/graphics/buttons.

Thanks!

**Comment by Lindaleunissen** [comment]
Just had a look at the Sites page, and I think, though copy needs tweaking, that the page lay-out will not change, so we could go ahead with it in this release. @Lynngre

**Comment by Lindaleunissen** [comment]
The content for this page has been on hold for a while. We've finally started adding content to the page, but it displays wrong on the front end. The carousel images and copy is stacked. See attached screen grab.
![screen shot 2017-07-21 at 10 16 32](https://user-images.githubusercontent.com/5338081/28457365-b7ede52a-6dfd-11e7-84ee-0ecccba1fae0.png)

**Comment by Lindaleunissen** [comment]
For clarification I have moved the previous update to a new issue number: #1180
