### ISSUE TITLE
Unable to insert images on website (Linda)

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#1005]
I'm not able to insert images in rich text frames (like a blog post).

If I click [add media] I'm able to upload an image to the library. I can then select that image and click [insert into post]. The media window will then close as usual, but the image doesn't appear in the rich text frame. 

In some cases (but not all) I am able to replace an existing image. (though if I remove it and try to re-insert it as above it doesn't work)

I can add images to image fields without any issues.

**Comment by Lynngre** [comment]
@samvthom16 could you check this issue please?  My user account has the same problem on both Akvodev & Akvo.org - may be WP version related but not sure.  I've had a look but don't see anything obvious.

**Comment by samvthom16** [comment]
@Lindaleunissen 
Can you check if this problem still persists because it works fine for my account?

**Comment by Lindaleunissen** [comment]
Yes, problem still exists. Working fine for others, but not for me and Lynn.

**Comment by Lindaleunissen** [comment]
It seems to be working at the moment. But will keep an eye on this.
