### ISSUE TITLE
Upload .eps images to image library

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#1006]
We have a bunch of updated and new logos that I'd like to add to the media page. At the moment we show a .png image, and link to the .eps images for different colour settings. 

The .eps images are hosted in the image library, but when I try to upload the new ones, the image library says it doesn't accept .eps format.

**Comment by samvthom16** [comment]
Most web browsers don't have support for eps files

**Comment by Lindaleunissen** [comment]
We already have .eps files uploaded, and I would like to add some more. If this is a browser issue, which would you recommend then?

**Comment by Lynngre** [comment]
#1006 fixed & closed
