### ISSUE TITLE
Media page: Logo background colour

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#1007]
When uploading new logos on the media page, can I add the black background myself? Or do you need to do that @samvthom16? If possible I would also like to add different coloured backgrounds (like orange for Caddisfly and Flow and green for Lumen)

(related to #1006)

**Comment by samvthom16** [comment]
@Lindaleunissen 
Can you upload a sample logo for reference?

**Comment by Lindaleunissen** [comment]
Please scroll down the page to existing logo's for reference: http://akvo.org/about-us/media-and-press/ 

For Flow I would also like an orange background, for RSR a blue one, etc. There are also logos that aren't on the site yet: Lumen, Caddisfly and Sites which need a black background, as well as a second colour that matches the logo (as described for Flow and RSR)

**Comment by samvthom16** [comment]
The content has been hard coded into the text-editor. We would need custom fields for adding logos with background.

**Comment by samvthom16** [comment]
http://www.akvodev.org/about-us/media-and-press/
The EPS files have not been uploaded through the backend. They are already included in the theme. If these images are to be made editable then we should enable the provision of uploading eps files.

**Comment by Lindaleunissen** [comment]
It's a one time change, not something that happens often (this is first time since we've had this website). So if hard coding is easier/quicker then custom fields, then that's fine.

**Comment by Lindaleunissen** [comment]
I've updated the .png logos to a smaller size as per @samvthom16 request. Any developments regarding the background colour yet?

**Comment by Lindaleunissen** [comment]
How is the backgrounds issue going? I'd like to add the new logos to the media page, but can't until this is fixed.

**Comment by samvthom16** [comment]
@Lindaleunissen please confirm the colors http://www.akvodev.org/about-us/media-and-press/?

**Comment by Lindaleunissen** [comment]
Thanks @samvthom16 
Most of the colours look good. Just not sure about the pink could you please double check that?
Akvo Pink: #DB87C9

If possible I'd prefer the black background to be replaced by a dark purple background
Akvo Dark Purple: #2C2A74

Here are also the other colour codes, could you double check just in case?
Akvo Orange: #DE8929
Akvo Green: #75B62D
Akvo Light Blue: #72CDFF

**Comment by Lindaleunissen** [comment]
I just noticed that the blue colour of the link doesn't work well on the coloured background. Can I change that colour myself in the backend, or do I need your help with that?

**Comment by samvthom16** [comment]
@Lindaleunissen Everything is hard coded in the page so you would need my help. Let me know what color you want it to be replaced with.

**Comment by Lindaleunissen** [comment]
@samvthom16 It's only a problem on the coloured backgrounds. So could you keep te font coloured as it is on the white and dark purple background, but only change it on the coloured (green, yellow, pink, blue, orange) background? Dark Purple #2C2A74 would probably come out best.

**Comment by samvthom16** [comment]
@Lindaleunissen the color of the links on the coloured have been updated.

**Comment by Lindaleunissen** [comment]
Looks great. Thank you @samvthom16.

@Lynngre This one is signed off and can be added to the next release.
