### ISSUE TITLE
23 Aug release: change tabs on RSR page

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#1008]
For the 16 August release, we would like to align the RSR tabs with the new Flow section that will go live in that release. 

Please can you move the SUPPORT tab to 3nd place, after FEATURES, and change the name of SUPPORT tab. Name still tbd; may be PARTNERSHIP or SERVICES  or PARTNER or EXPERTISE.

**Comment by Lynngre** [comment]
Release is happening on 23 August
