### ISSUE TITLE
New Flow product page

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1011]
Create a Flow product page in the same style as the RSR product page.  @Lindaleunissen to supply updated mockup.

**Comment by Lindaleunissen** [comment]
Updated mock up can be found here: https://www.dropbox.com/s/ibcfsygzoahqsun/Flow%20page%20mockup%2012-08-2016.pdf?dl=0

Page 1-3: overview page with different slide images
Page 4: Services
Page 5: Features
Page 6: Pricing
