### ISSUE TITLE
Media page: Logo menu

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#1045]
On top of the logo section on the media page there is a menu that is still from the old style product pages. Can you please remove that? See screen grab below. 

<img width="1273" alt="screen shot 2016-09-16 at 15 05 02" src="https://cloud.githubusercontent.com/assets/5338081/18588589/03c71164-7c1f-11e6-9caf-08daa64bc8a3.png">

**Comment by samvthom16** [comment]
Removed in https://github.com/akvo/akvo-web/issues/1007
