### ISSUE TITLE
Media page: brand book

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#1046]
I'm working on a brand book that should be added to the media page, in the logo section. Ideally I want to do something like this: https://issuu.com/carol_pistone/docs/barnes___noble_issuu/1 , so it's viewers can flick through the pages. Is it possible to do something similar?

**Comment by Lynngre** [comment]
@Lindaleunissen this is possible using a flipbook type plugin. There are many different types. Could we have a quick look at a few together?

**Comment by Lindaleunissen** [comment]
@Lynngre I had a look at the flip books you shared with me. 
I really like [FlippingBook](https://wordpress.org/plugins/flippingbook/) - though it seems to load extremely slow for me, so it would need some testing. It also has FlippingBook branding on there, though from what I can see it doesn't look that bad.

[Flowpaper Light](https://wordpress.org/plugins/flowpaper-lite-pdf-flipbook/) is nice, also has their branding on it (unless we buy the full version).

I also like [Yumpu ePaper publishing](https://wordpress.org/plugins/yumpu-epaper-publishing/). 

Some of the other ones, like WordPress PDF light viewer don't look that nice, so would be great if we can implement one of the ones I mentioned above. 

I've attached a preliminary version of the brand book for you to test the plug-ins with. 
[brandbook 16-09-2016 external version.pdf](https://github.com/akvo/akvo-web/files/497798/brandbook.16-09-2016.external.version.pdf)

**Comment by Lynngre** [comment]
https://github.com/akvo/akvo-web/pull/1065
