### ISSUE TITLE
Footer alignment on some mobile devices

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1061]
On older devices such as Samsung S3/S4 & Iphone5 the footer is out of alignment. Using http://quirktools.com/screenfly/ to test.

![screen shot 2016-10-19 at 16 53 19](https://cloud.githubusercontent.com/assets/2675262/19524091/e3ecc3f8-961c-11e6-8ff7-26f722dde2a6.png)
![screen shot 2016-10-19 at 16 53 06](https://cloud.githubusercontent.com/assets/2675262/19524111/f4f5f156-961c-11e6-824a-606dcf5d7e2c.png)
![screen shot 2016-10-19 at 16 53 00](https://cloud.githubusercontent.com/assets/2675262/19524122/fcbac15a-961c-11e6-87db-3d39a67ac6a7.png)
![screen shot 2016-10-19 at 16 52 20](https://cloud.githubusercontent.com/assets/2675262/19524152/0cd440ac-961d-11e6-8920-99710e23e975.png)

**Comment by samvthom16** [comment]
@Lynngre for smaller screen devices we can vertically stack and center align them.
