### ISSUE TITLE
New partner page section

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1086]
Required to start with mvp
- [ ] landing page template containing search area, a few tabs with 1 containing boxes for case studies & 1 with contact information 
- [ ] search/filtering front end should have filter for Location/Tool/Sector/Organisation or Partner the RSR database contains data for all of these (see the advanced filter on rsr.akvo.org) besides the tool filter which is just our existing products.
- [ ] search/filtering backend incl. data in db for preexisting options/tags
- [ ] creation of a pre-filtered url (has search parameters included) which allows user to go directly to the specific data (for example someone who needs to see 'page' for a specific region only)
- [ ] case study template
- [ ] at a later stage look at including a map

Considerations:
- What happens on the page when each filtering option is selected? (How do displayed items change?).  What happens when the filtering is changed again?
- How do we set these changes to happen in the backend based on content editors work? Preexisting tags, keyword area, etc?
- What happens to the url when each filtering option is selected? What happens when filtering is changed again?
- How many case study widgets on each page?
- Ensure high quality but full image on the case study widget boxes
- What does the case study page template look like?  Where does the content come from?
- Do we include maps? If yes, which type of mapping option & how do we make the map relevant to the search/filtering page that loads?

**Comment by samvthom16** [comment]
@Lynngre had a quick question, if filtering is outside the two tabs then how does the tab for contact area change?

**Comment by Lynngre** [comment]
After a discussion around filtering by the visitor & what would load when particular filters were selected the following was decided for the mvp:

- No filter by organisation
- No filter by products.
- No tabs are required

- [ ] filtering by 'Region' & 'Sector' is required only for mvp

- [ ] 'Capture, understand, share' would be shown on case study widgets by coloured line (same as currently done on the homepage carousel). So blue, yellow, etc

- [ ] Global partner page section (use page 9 from latest wireframe for idea of layout) would have widget boxes with tagged case studies & the filter bar above
![screen shot 2016-11-18 at 09 18 00](https://cloud.githubusercontent.com/assets/2675262/20423349/0552f624-ad70-11e6-90d0-904fb85c9079.png)

 - [ ] Case study template:  backend needs to be flexible with list of things which could be displayed (user can select which options will be displayed ie. latest blog post excerpt & video, or only video for example. Display summary of project from Akvo chum possibly? Titles for each section? (Page13 of the latest wireframe for layout guide).  NEEDS SOME ADDITIONAL INPUT FROM COMMS but we can get started on this for now.
![screen shot 2016-11-18 at 09 19 20](https://cloud.githubusercontent.com/assets/2675262/20423550/4739e3a8-ad71-11e6-8f3e-e915fdcf3573.png)


-[ ] Button is required for contact us.  THIS NEEDS MORE CLARITY FROM COMMS
 
- [ ] Regional template: same as global partner section landing page but case studies tagged with particular region selected in filter will be loaded.

- [ ] Comms would like to use one of the widgets for 'case studies' to actually not be a case study widget but be a LOGO widget which links you to relevant logos, logos link to organisation. THIS NEEDS MORE CLARITY FROM COMMS, unsure what this would link to.

**Comment by Lindaleunissen** [comment]
A lot of the questions above are addressed in the document below. There are also some questions still open, but it should help you already. Mano has also set up a spreadsheet with requirements. You can find them below. 

Feedback on questions above:
https://docs.google.com/document/d/1CzLd6VUUEETDGwBUFow73Hpv2-eS_R7doE6D4itkoDc/edit?usp=sharing

Requirements:
https://docs.google.com/spreadsheets/d/1O_Z2W3sCwuL4KoIm7uER_hWXd-feZNqX5K6YZLVMnaU/edit?usp=sharing

**Comment by samvthom16** [comment]
[advanced-custom-field-export (1).zip](https://github.com/akvo/akvo-web/files/1491104/advanced-custom-field-export.1.zip)

**Comment by samvthom16** [comment]
https://github.com/akvo/akvo-web/issues/1294
