### ISSUE TITLE
Media page displaying incorrectly

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#1091]
There seems to be a problem with the logos on the Media page.  This happened yesterday when I restored an earlier version to recover some missing media coverage items that were lost when the page was updated with the new logos. I copied the missing items and then restored to the latest version. The latest version is there but with lines across the logos. Also Emily added some additional media coverage items to the page yesterday pm US time.

**Comment by samvthom16** [comment]
@JoPratt please add a screenshot too for more clarity

**Comment by Lynngre** [comment]
@samvthom16 it's on Safari

![screen shot 2016-11-30 at 14 03 34](https://cloud.githubusercontent.com/assets/2675262/20753266/d7cbdcd0-b705-11e6-9768-7847600a7523.png)
![screen shot 2016-11-30 at 14 03 40](https://cloud.githubusercontent.com/assets/2675262/20753267/d7e40418-b705-11e6-8fb7-5680a3b7161e.png)

**Comment by samvthom16** [comment]
@Lynngre the fix is there in this commit https://github.com/akvo/akvo-web/commit/05d36fd566f08b61c015d395a01a425a3d9216b2. We would need a release
