### ISSUE TITLE
Improvements to site speed

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1099]
General testing/improvements to site speed incl. testing caching.

**Comment by samvthom16** [comment]
Speed audit
https://tools.pingdom.com/#!/ezZ1wj/akvo.org
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fakvo.org%2F&tab=desktop

**Comment by samvthom16** [comment]
Compress images using wp-smush.
Styles for small screen devices can be separated in a different stylesheet to prevent render blocking. 
Styles and Js can be minified to decrease the payload. Query string can be removed from external js and combined together. 
Browser caching expiration time can be increased using W3TC. 
Check for plugins that use different versions of Jquery and remove the inconsistencies.

**Comment by Lynngre** [comment]
@samvthom16 to remove wp-smush, using kraken.io instead.
