### ISSUE TITLE
Slow loading first few seconds

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1104]
There are two issues when trying to load the homepage.

1.  GET bx_loader.gif takes 4-5 seconds to lookup which results in a 404 

![screen shot 2017-01-10 at 15 28 25](https://cloud.githubusercontent.com/assets/2675262/21809798/78a09692-d749-11e6-8396-68e6d1522992.png)

2. GET admin_ajax.php takes well over 4 seconds to lookup too
![screen shot 2017-01-10 at 15 29 18](https://cloud.githubusercontent.com/assets/2675262/21809829/a7c188d2-d749-11e6-99cc-939ce461ab12.png)

**Comment by samvthom16** [comment]
Some plugins are causing slow load time. The main players are Optimizely and Wordpress Fence

**Comment by Lynngre** [comment]
@samvthom16 thanks will check.  Optimizely I can remove but wordfence we def need for security.

**Comment by Lynngre** [comment]
Adding a performance profiler to find the first 2.4-3s response when loading akvo.org

**Comment by Lynngre** [comment]
Link: <http://akvo.org/wp-json/>; rel="https://api.w.org/" appears in the first header request response

https://wp-mix.com/wordpress-disable-rest-api-header-links/ has some info on this. We are not using the rest api in our site.

We will remove all the unnecessary overhead from wp included in our theme.

**Comment by Lynngre** [comment]
Adding database (Mysql) & php performance reporting plugin.
https://wordpress.org/plugins/mywebtonet-performancestats/
