### ISSUE TITLE
Media page logos

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1134]
Quality of logos is severely degraded, only noticeable when downloading & using the file.

@samvthom16 we need to look at how those logos were added, they should be of highest quality.

Adding @Lindaleunissen so that you two can work together on getting the expected result.

**Comment by samvthom16** [comment]
@Lynngre 
Kraken.io plugin has optimized all the images, hence the downgrade in quality.

**Comment by Lynngre** [comment]
@samvthom16 the lower quality was noticed before the kraken.io was released & manual update of images began.  So this cannot be.

**Comment by samvthom16** [comment]
@Lynngre 
In that case we will have to repload the images again

**Comment by Lynngre** [comment]
FIxed
