### ISSUE TITLE
W3 Total cache - team page

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1161]
Team page is empty (no page source code) when W3 total cache is activated, even though the plugin has been set to ignore this page.
Is something loading initially which is being cached & blocking the page from loading?

**Comment by Lynngre** [comment]
@samvthom16 any news on what's going on here?

**Comment by samvthom16** [comment]
@Lynngre I had to disable the object cache as object cache runs well with memcache or similar installed on the server

**Comment by Lynngre** [comment]
Object cache under the main settings is enabled by default when updating the caching plugin.
