### ISSUE TITLE
New Lumen page: testimonial width

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#1175]
The width of the testimonials we use on the other product pages is very narrow, which makes the testimonials look very long (see attached example). Please adjust the width of the text, and reduce it to 2 columns. It be nice if we can add a second row of 2 testimonials if need be. 

<img width="1147" alt="screen shot 2017-07-21 at 10 41 34" src="https://user-images.githubusercontent.com/5338081/28458398-8516fa84-6e01-11e7-9658-2fc4ba9e7d76.png">

**Comment by Lindaleunissen** [comment]
Much better on Akvodev. Once we start populating it with content we may still have to reduce it to 2 columns, but for now this is ok. Thanks!

**Comment by samvthom16** [comment]
Due to lack of testimonials, change the number of columns to 1 and increase the width.
