### ISSUE TITLE
Lumen product page: Background colour

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1191]
On mobile devices the background colour of the other product pages is white with a 'grey bar' containing the breadcrum.

On mobile devices the Lumen product page is completely grey with the Lumen logo being displayed against a white background.

This needs to be corrected to white with grey breadcrumb bar, the same as the other product pages.

<img width="1067" alt="screen shot 2017-09-21 at 11 20 38" src="https://user-images.githubusercontent.com/2675262/30688946-ccb6a5d0-9ebf-11e7-8ef0-784276dda176.png">

**Comment by samvthom16** [comment]
@Lynngre can you help me recreate this bug?
