### ISSUE TITLE
New Lumen Product Page: Icons

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1193]
The icons on the Lumen overview page are not resized/responsive on mobile devices. Compared to icons on the other product pages they are huge.

<img width="1017" alt="screen shot 2017-09-21 at 11 23 38" src="https://user-images.githubusercontent.com/2675262/30689746-2930b1fa-9ec2-11e7-8045-c8eeb227229a.png">

**Comment by samvthom16** [comment]
The icons in lumen product page are bigger compared to other product pages.
