### ISSUE TITLE
'Latest RSR update' no image provided when the update contains video

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1194]
When an RSR update contains a video, no image is provided as a featured image via the API so the widget image area is empty.

What would the options be for filling that empty space?

https://rsr.akvo.org/en/project/2335/update/19436/ . is an example.
<img width="1194" alt="screen shot 2017-09-21 at 15 00 04" src="https://user-images.githubusercontent.com/2675262/30696939-a20342da-9edd-11e7-85fb-efdb1af37c7b.png">

**Comment by samvthom16** [comment]
@Lynngre we could use a default image

**Comment by samvthom16** [comment]
No longer needed with the new Homepage 2018 release
