### ISSUE TITLE
Setup malicious host denial

### ISSUE THREAD

**Issue by osgl** [akvo/akvo-web#12]
Install and configure denyhosts on the new akvo.org and RSR servers. Log denied hosts instead of sending email alerts.

**Comment by Lynngre** [comment]
@osgl Is this ok to close?

**Comment by osgl** [comment]
Not yet.

@carlio or @orifito -- do we have any malicious host prevention in place with the current provisioning configs or a strategy for minimising such activity?

**Comment by carlio** [comment]
We enforce key-based auth only now, so we don't have to worry about bruteforce password attacks.

**Comment by osgl** [comment]
Ok, I'll close this.
