### ISSUE TITLE
New regional page - 'other hubs' dynamic graphic

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#1233]
Please change SEAP text to say Selamat datang (instead of capitalised).
Also please centre this text to the SEAP button, as is done with all the other buttons.

**Comment by Lynngre** [comment]
@samvthom16 update the text to sentence case please, not uppercase. 
<img width="1237" alt="screen shot 2018-02-20 at 20 41 37" src="https://user-images.githubusercontent.com/2675262/36445415-81d5eff8-167e-11e8-97fb-b952395963cd.png">

**Comment by Lynngre** [comment]
Fixed for release, currently on staging.
