### ISSUE TITLE
Product pages template

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#1234]
We're updating the RSR page, but the current page is much older than the other product pages, and has less options and flexibility than for example the Lumen or Caddisfly page. 

Can we update ALL product pages so that we can
- Change the header text on the tabs
- Change the colour of the last header tab (dropdown menu)
- Have 4 columns on the overview tab (with the flexibility to have less)
- Are able to set a colour (dropdown again) for the last column on the overview tab
- Are able to insert counters on the bottom of the overview page
- Remove image headers on the features tab (currently we get a broken image symbol if we remove them on the RSR page)
- The basic setup for each page is overview, services, features, get [product name]
- Services and features tab are basically the same, with the option to add (or not add) fa icon codes
- Get [product name] tab contains a form

This change should also cover issue #1228 #1206 #1193 #1192 #1191 #1190

**Comment by samvthom16** [comment]
@Lindaleunissen 
Taking FLOW as the reference, sections withing the OVERVIEW TABS:
1. Carousel (collection of images and text)
2. Overview 4 Columns, with the ability to set a color on the last column from a dropdown 
3. Overview buttons - video, get in touch, etc
4. Testmonials
5. Counters

**Comment by Lindaleunissen** [comment]
@samvthom16 That is correct. 
The colour of the buttons changes per product though. 
Maybe there is one colour dropdown option at the top of the page that sets the colour for the page, in stead of multiple dropdowns. (we will only have to set 1 colour per page, same colours as the lines under the images on the current homepage).

**Comment by Lindaleunissen** [comment]
Also (as a side note), as we will be changing the order of tab 2 and 3 in some cases, it may be easier to just call the tabs 1, 2, 3, 4. Then in the title box (which is currently not on all tabs) we can set the text that will appear on the tab on the website.
