### ISSUE TITLE
New regional page - language toggle

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#1236]
There is no language toggle on the pages at the moment. 
Only needed for Americas and West Africa pages. Other pages don't need a toggle. 

@loicsans to decide what the best place is to put it.

**Comment by samvthom16** [comment]
[regionpage_2017.pdf](https://github.com/akvo/akvo-web/files/1681195/regionpage_2017.pdf)
For reference

**Comment by Lynngre** [comment]
@samvthom16 the language toggle needs to be in smaller font size.

**Comment by Lynngre** [comment]
What if there is no translation?

**Comment by Lindaleunissen** [comment]
Ideally there wouldn't be anything visible if there is no translation.

**Comment by Lynngre** [comment]
@samvthom16 the language toggle needs to be at the top of the image & much smaller font size.
![screen shot 2018-02-22 at 16 45 35](https://user-images.githubusercontent.com/2675262/36548209-fc94c1a2-17ef-11e8-9443-da589265888b.png)
