### ISSUE TITLE
Regional page: projects white text over image doesn't work 

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1257]
<img width="1270" alt="screen shot 2018-02-20 at 20 29 34" src="https://user-images.githubusercontent.com/2675262/36445005-2c451c54-167d-11e8-8c6f-ce07aae839c4.png">
@Lindaleunissen white text on the image doesn't work when not hovered over.  Is that what we want?  Or do we just not want any text shown until someone hovers?

@samvthom16 what are the options of adding a dark overlay on hover?

**Comment by Lindaleunissen** [comment]
Can you do something like this:
<img width="1075" alt="screen shot 2018-02-21 at 09 19 02" src="https://user-images.githubusercontent.com/5338081/36472027-5b6e6a88-16e8-11e8-8367-c1b6f43414df.png">

(see here: http://www.ahoyamsterdam.nl/best-bars/)

**Comment by Lynngre** [comment]
Ok, so the text should have a darkened band around it at all times. @samvthom16 could you check that please?

**Comment by Lynngre** [comment]
@Lindaleunissen would you like to define the hex colour code for the overlay?
![screen shot 2018-02-23 at 10 04 53](https://user-images.githubusercontent.com/2675262/36586271-6dcf033c-1881-11e8-825b-1d44ad40b6dc.png)

**Comment by Lindaleunissen** [comment]
It should fe 000000 at 70% (so 30% transparency)

**Comment by Lynngre** [comment]
Great thanks
