### ISSUE TITLE
Regional pages: Background

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1258]
Background image is too large at recommended size. @Lindaleunissen used 400x400 here & that seems to work much better. @samvthom16 could you check please?

<img width="1352" alt="screen shot 2018-02-20 at 20 34 10" src="https://user-images.githubusercontent.com/2675262/36445108-8a27c132-167d-11e8-9fb3-fb1c63ed099f.png">

Example of recommended size:

<img width="1374" alt="screen shot 2018-02-20 at 20 34 04" src="https://user-images.githubusercontent.com/2675262/36445124-92bcc6f8-167d-11e8-83e8-d800078205f2.png">

**Comment by Lindaleunissen** [comment]
Actually, it needs to be the size of the first example @Lynngre posted. It didn't look like that on my screen yesterday. Looking at it today some of them display correct, some don't still look like the 2nd image, which is too large.

**Comment by Lynngre** [comment]
@Lindaleunissen the first image is the 400x400 on West Africa test page.

**Comment by Lindaleunissen** [comment]
The second is the 400x400 on the Americas page. Weird huh?

**Comment by Lynngre** [comment]
First background is actually larger file size.  400x400 is too small and means that the image is stretched to fit. Full size should be used.
