### ISSUE TITLE
Title not adhering to padding

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1276]
https://github.com/akvo/akvo-siteorigin-widgets/issues/1

**Comment by Lynngre** [comment]
Think it's the same for the content box shown here:  out of alignment again.

![screen shot 2018-03-26 at 15 30 32](https://user-images.githubusercontent.com/2675262/37909286-c6344446-310a-11e8-8ddf-ee3fa8f78abf.png)

**Comment by samvthom16** [comment]
Fixed through customize:
/* MICROSTORY WIDGET TITLE */
.fullBlack .micro-story .widget-title{
	max-width: 1000px;
	margin: 0 auto;
	padding: 30px;
	padding-bottom: 0;
	box-sizing: border-box;
}
@media( max-width: 768px ){
	.fullBlack .micro-story .widget-title{
		padding: 15px;
		padding-bottom: 0;
	}
}
