### ISSUE TITLE
Twitter cards

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1282]
No image is appearing when our domain is added to a tweet. Our domain is whitelisted & validated correctly by Twitter but it seems they have updated something on their side. There needs to be a meta tag added to your page header for all your pages to allow for this summary card to appear when your url is tweeted.  
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image.html

<img width="1142" alt="screen shot 2018-04-12 at 18 55 42" src="https://user-images.githubusercontent.com/2675262/38698912-e7b5f422-3e96-11e8-90fd-2a563a6b6307.png">

**Comment by samvthom16** [comment]
@Lynngre now we can add twitter cards through Yoast. https://yoast.com/twitter-cards/

The specific image for any page can be added through the backend. In our case, for the homepage it can be added in the yoast settings here https://akvo.org/wp-admin/post.php?post=32980&action=edit&lang=en

**Comment by Lynngre** [comment]
Featured image needs to be selected for each page, otherwise the page card does not have an image attached when tweeted.
