### ISSUE TITLE
Tweetable plugin

### ISSUE THREAD

**Issue by samvthom16** [akvo/akvo-web#1285]
Pre-written tweet, that people can easily adjust and sent.

**Comment by Lindaleunissen** [comment]
The plugin you shared with me on the staging area is perfect. I showed Alvaro and he is happy with it. Can we use it in blogs? That will be the main place where we want to use it.

**Comment by samvthom16** [comment]
Plugin to be used: https://wordpress.org/plugins/better-click-to-tweet

**Comment by samvthom16** [comment]
@Lindaleunissen the plugin has been uploaded on the live site. 

Here's how you format the shortcode:
[bctt tweet="Meaningful, tweetable quote."]
