### ISSUE TITLE
Notes about new JSON plugin version

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-web#317]
Small list of issues noted when using the latest version of the JSON plugin.

* When deleting an existing plugin instance the redirect back to the feeds listing page does not always work, instead the redirect gets into a loop redirecting to the redirect page
* The **Save and close** buttons does not always redirect back to the feeds list
* The plugin instance scripts are not visible after saving. They get saved and run correctly (if they are correct...) though
* The **Preview** still does not work, I don't even know *how* it's supposed to work

**Comment by Lynngre** [comment]
#317 closed

JSON data plugin is being completely rewritten.
