### ISSUE TITLE
Pricing page update

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#336]
In a website meeting held in June it was agreed that the text on the pricing page needs to be simplified.

**Comment by Lynngre** [comment]
@JoPratt to update progress after Stockholm meeting.

**Comment by JoPratt** [comment]
I asked Thomas about this - the pricing work is still not sufficiently progressed to be able to revise the pricing page yet. Most of the work to date has focussed on FLOW as well, so even when it's done, they'll still need to look at RSR as well.

**Comment by JoPratt** [comment]
Comms is working on the content for 31st March release. Linda has created a rough version of a graphic, getting feedback from Thomas. In progress.

**Comment by Lynngre** [comment]
Deadline for Pricing page content/layout is for the end of today, 7 April.  Release is Thursday.

**Comment by JoPratt** [comment]
Additional improvements to be included in April 28th release:

- engagement button to lead to form to capture info and/or send an email
- add content behind three boxes at bottom of page and make them clickable
- add more detailed pricing info for other products besides FLOW

**Comment by Lynngre** [comment]
#336 fixed & closed, there are further issues for the pricing page, but will be dealt with seperately.
