### ISSUE TITLE
Change "Extended Team" to "Extended team" on Meet our team page

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#432]
Please can you change "Extended Team" to "Extended team" in the page navigation bar. 
We use sentence case elsewhere on this page and the rest of the site. 

Low priority.

**Comment by Lynngre** [comment]
@gabemart or @loicsans this is a really small change please could we add this?

**Comment by loicsans** [comment]
@Lynngre ok, will do

**Comment by Lynngre** [comment]
#432 fixed & closed
