### ISSUE TITLE
JSON plugin cache house keeping

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-web#451]
The JSON plugin doesn't remove old JSON files from the cache. This reults in a lot of old JSON files, and sooner or later they'll fill up the disk! (The JSON file for the RSR map in 2MB, fetching it once an hour means around 50MB per day -> 1.5GB per month!)

The plugin should be able to remember the ID of the JSON cache file it created, and either delete it when fetching new data or just update the existing file rather than creating a new one.

**Comment by zzgvh** [comment]
The patch is now running on akvodev.org. After deploying, I visited /seeithappen and /seeithappen/all-rsr-project-updates to refresh the JSON data cache. I then deleted all older data-NNNN.json files using this little command line: ```ls * | grep -v file_you_want_to_keep | xargs rm -rf``` where file_you_want_to_keep is replaced with the latest JSON file for each instance of the plugin data.

**Comment by zzgvh** [comment]
Well that wasn't all that bright...since I managed to delete the templates :stuck_out_tongue: The revised command should be ```ls *.json | grep -v file_you_want_to_keep | xargs rm -rf```

**Comment by zzgvh** [comment]
@eefsparreboom  It seems there's a regression in the new version. The query parameters are stored in lowercase in the DB again, resulting in problems with params like idSite.

@osgl  and @eefsparreboom I haven't been able to test the actual functionality of the patch, that new data pulled from the APIs is stored in the existing cache file rather thanö creating a new file. This is because the cron job doesn't seem to do its job and I  can't determine if that's a problem with the plugin or the server setup. I've tried using WP cron too, but to no avail.

**Comment by Lynngre** [comment]
#451 closed

JSON data plugin is being completely rewritten so this is no longer relevant.
