### ISSUE TITLE
Line breaks in See it happen - dashboard area

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#477]
Lines break in an odd place when the side bar is open in Safari. (see image) 
Would be nicer if €xxx was on first line, and million on the second line. 

![screen shot 2014-12-03 at 10 42 27](https://cloud.githubusercontent.com/assets/5338081/5279113/1895789a-7ad9-11e4-9332-b8eed0c1b0e1.png)

**Comment by Lynngre** [comment]
#477 fixed - as far as possible.
