### ISSUE TITLE
Add FLOW users bulletin archive and sign-up box to FLOW help page

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#479]
Please can we add a sign-up box and link to latest issue and/or archive of previous issues of the FLOW users bulletin, which is distributed via mailchimp, to the FLOW help page.

Could we include an explanatory text above the sign up form:
"Sign up to our ad hoc bulletin telling you about new features, product changes, and other information that will help you to use Akvo FLOW effectively. You can unsubscribe at any time."

Would you need us to retrieve the code for the sign up form and archive from Mailchimp? It's possible to create a sign up form with intro text in mailchimp and embed it - not sure if that's the best way to do it.

**Comment by loicsans** [comment]
This is not going to be done today. Requires some work.

**Comment by Lynngre** [comment]
Ok will add to the next release.

**Comment by Lynngre** [comment]
We should include info on signing up to the @AkvoStatus twitter feed here too as that's where these notifications are made in real time.
