### ISSUE TITLE
Reorganise Contact us page

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#486]
Having Thomas as the 'Technical' contact is not workable, but it's not clear who/what to replace him with. Lissy also gets a lot of irrelevant email from featuring on the Contact us page. 

People contact Akvo for numerous reasons, which don't divide neatly into centralised "Partnerships", "Communications" and "Technical". I've started a doc listing reasons why people contact us and how their enquiry should be directed: https://docs.google.com/document/d/1Y17LhFvnjxzZph2D-zjjI5OFTJPZvJhM8ikniuV4z4w/edit 
Alvaro is looking at it and expanding it and discussing with Thomas. 

This connects with engagement funnels work too.

**Comment by Lynngre** [comment]
I think this was more about getting a link to Help/support on the contact page instead of removing Thomas as Technical contact?

**Comment by Lynngre** [comment]
@JoPratt to chat to @bjelkeman when in Stockholm

**Comment by JoPratt** [comment]
The above issues have largely been solved with edits I made to the three contact boxes under the map.
However we would still like to make some simple improvements to this page in the 31st March release:

1) Map - Linda will provide a new map graphic without any coloured-in countries to replace the current map.

2) hub listings layout - please can we have 2 columns of text. This should neaten up the spacing between each hub listing and also give us space to add brief additional, externally relevant info in the first column about what the office does e.g. Delhi/Asia hub: "Sales and support for Indian sub-continent and surrounding areas." Amsterdam: "Central administration and international sales and support."

3) Please can we add the google maps links back in again.

**Comment by Lindaleunissen** [comment]
Sent vector graphic of the map to @gabemart. Happy to turn into JPG or PNG if you let me know the dimensions.

**Comment by JoPratt** [comment]
Google map links are back but points 1 & 2 still to be actioned.

**Comment by Lynngre** [comment]
@loicsans & @Lindaleunissen please check point 1 & 2

**Comment by loicsans** [comment]
1 & 2 Fixed

**Comment by Lynngre** [comment]
#486 fixed & closed
