### ISSUE TITLE
JSON data folders, style.css & template.phtml files

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#514]
'/var/akvo/homepage/data/json-data/cache' needs to have the following folders deployed to it:

akvopedia-analytics  openaid-orgs	rsr-projects-global-map
akvopedia-articles   right-now-in-akvo	rsr-update-count
openaid-activities   rsr-many-updates	rsr-updates

These folders contain style.css & Template.phtml files which need to exist upon deployment of the site.  the 'data.....' files will be created by the Json plugin again, but the others will not.

Without these folders & the files the Seeithappen page is broken.

**Comment by Lynngre** [comment]
@carlio @osgl how do we get these included and only include the last 'cached data' from each folder but all style.css & template.phtml files?

**Comment by carlio** [comment]
Hi @Lynngre ,

It doesn't make a lot of sense to do it ths way. The cache folder is for temporary data that can be lost and replaced, hence the name. Code (including stylesheets and HTML) should be deployed along with everything else. Can you move those .css and .html files into the plugin's code directory and reference them from there instead?

**Comment by Lynngre** [comment]
The cache files - style & template files are generated in the DB by creating the slugs.  

These should not be 'deployed' as the DB is not deployed.

Replace the template & style files from the repo which can be found at https://github.com/akvo/akvo-web/tree/develop/code/wp-content/themes/Akvo-responsive/json_data_templates

What we should do is create a script to keep only the latest .data & delete all .data from each folder.

**Comment by Lynngre** [comment]
No longer valid as the JSON data plugin is being completely rewritten.

#514 closed
