### ISSUE TITLE
Add 'million' in Akvopedia & FLOW stats

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#515]
Allow the stats for FLOW datapoints & Akvopedia visits to be entered as 'million' with decimal point.

![screen shot 2015-02-04 at 12 22 55](https://cloud.githubusercontent.com/assets/2675262/6039622/f63fb5a0-ac68-11e4-878d-32101411c9e3.png)

**Comment by loicsans** [comment]
Isn't it loaded via the JSON plugin?

**Comment by loicsans** [comment]
np, I figured this out.

**Comment by loicsans** [comment]
![screen shot 2015-02-13 at 10 58 07](https://cloud.githubusercontent.com/assets/1717219/6184817/4281eb06-b36f-11e4-90a0-061e6c4106c1.png)
Fixed

@Lynngre, can you check on live and close

**Comment by Lynngre** [comment]
Thanks @loicsans think the Akvopedia ones should be the same as the Flow data point one,  (ie. only 2 digits after the decimal point).

**Comment by Lynngre** [comment]
#515 fixed & closed
