### ISSUE TITLE
Revise Akvopedia product page to reflect 5 portals not 4

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#517]
The content and layout of the Akvopedia page refers to 4 portals, whereas there are now 5 (Decision & assessment tools is fifth).

To correct this we need to redesign the page a bit (Linda/Loic/Gabe) because there are 4 portal boxes. Also need to edit and update the copy (JP) and change the menu bar item which says "Four portals" (Loic/Gabe). Assigning this to Linda as I think her bit comes first.

Do we want to think about how we could make some of these kinds of changes doable by comms in future? Not sure if there would be sufficient need, but worth considering at least. If menu bar just says "Portals" then we wouldn't need to change that again if a new portal is added.

**Comment by Lynngre** [comment]
@JoPratt could this be ready for 17 March?

**Comment by JoPratt** [comment]
Planning this for next release involving content so 31st March

**Comment by Lindaleunissen** [comment]
Draft icon for the portal is ready. I'll be finalising it this week. @gabemart Is it possible to add room for a 5th icon? There will be a 6th portal added soon too, so maybe 2 rows could work? Three icons on the first line and two on the second line, so we can add a 3rd there when the sixth portal goes life.

**Comment by gabemart** [comment]
@Lindaleunissen That looks pretty straightforward. If there are 6 icons, we could have 2 rows of 3 on desktop and 3 rows of 2 on mobile. If there are five, it might be a little more complex to arrange nicely, but I'm sure it's doable. I will aim to take a proper look at this by the end of the week

**Comment by gabemart** [comment]
I will need to update the custom fields on Akvodev once the change is merged.

@loicsans could you take a look at the PR?

**Comment by gabemart** [comment]
@JoPratt this is now live on akvodev: http://www.akvodev.org/products/akvopedia/

**Comment by Lynngre** [comment]
#517 fixed & closed
