### ISSUE TITLE
Profile entries higher than min-height cause misalignment on About page

### ISSUE THREAD

**Issue by gabemart** [akvo/akvo-web#518]
http://www.akvo.org/about-us/team/

Any entries higher than the min-height cause misalignment the row below.

Possible fixes:

* bump the min-height from 205px to 210px, but any profile entries in the future higher than 210px will cause the same problem

* specify a height rather than a min-height

**Comment by Lynngre** [comment]
@gabemart & @loicsans this issue doesn't seem to be fixed on Akvodev (or akvo.org).

**Comment by loicsans** [comment]
@Lynngre it does look fixed for me on akvodev. Have you tried clearing your cache?

**Comment by Lynngre** [comment]
#518 fixed & closed
