### ISSUE TITLE
Add Akvo Staff handbook to Working at Akvo page

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#525]
Please can we add a hyperlink to the staff handbook in a sentence at the end of the 3rd para of the intro section to the Working for Akvo page:

Read more about working for Akvo in our >staff handbook<.

The handbook has been uploaded to Wordpress but I can't add a link in this section.

**Comment by Lynngre** [comment]
'staff handbook' currently links back to the 'working at Akvo page'.

**Comment by gabemart** [comment]
@Lynngre I had to manually update the page in WP after the template change was merged in. Should be working now

**Comment by Lynngre** [comment]
#525 fixed & closed
