### ISSUE TITLE
Contact us - link to google map location

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#526]
Add a link to the location on google maps of each hub.

http://akvo.org/contact-info/

**Comment by Lynngre** [comment]
@gabemart or @loicsans is this possible for tomorrow?

**Comment by gabemart** [comment]
@lynngre yes, I will do this now

**Comment by gabemart** [comment]
@Lynngre Changes now up on AkvoDev - http://www.akvodev.org/contact-info/

I just did a naive search for each address in Google maps, so someone may want to double check they're actually pinpointing the correct location! The link and the text for each link is updatable through the wordpress page

**Comment by Lynngre** [comment]
@gabemart thank you!  @JoPratt please check.

#526 fixed & closed
