### ISSUE TITLE
Image alignment on RSR Product Page

### ISSUE THREAD

**Issue by adriancollier** [akvo/akvo-web#555]
Some of the images in the product page are aligned to the left and this looks a bit strange:
![screen shot 2015-03-10 at 12 05 36](https://cloud.githubusercontent.com/assets/1426234/6573700/ca9a58c2-c71d-11e4-961a-454ab1399dfd.png)
I think the page would display cleaner if these images were centrally aligned.

**Comment by JoPratt** [comment]
This is what it should look like and what it looks like for me in Chrome. What browser/device are you using, Adrian?

![screenshot 2015-03-11 11 20 33](https://cloud.githubusercontent.com/assets/4302250/6595285/bea1c8e8-c7e0-11e4-8cfb-11eaecf2cb41.png)

**Comment by adriancollier** [comment]
This is in Firefox v36 - I see the same as you in Chrome, so it does look like a browser issue.

**Comment by Lynngre** [comment]
On Firefox v36 too, but don't have the same issue as @adriancollier possibly cache issue?
or possibly something to do with responsiveness specifically in FF?   

![screen shot 2015-04-07 at 12 26 54](https://cloud.githubusercontent.com/assets/2675262/7021417/85bb8d1a-dd21-11e4-895c-527df4d23442.png)

**Comment by adriancollier** [comment]
This is resolved now for me too.

**Comment by Lynngre** [comment]
#555 closed
