### ISSUE TITLE
Revise and update Foundations page

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#558]
Improve page design (it's ugly).

Add India and Singapore. 

Aiming for late April '15 release.

**Comment by Lynngre** [comment]
@JoPratt do we have content for India & Singapore?

**Comment by Lynngre** [comment]
@JoPratt  let's setup a meeting for the JSON data plugin side of updating this page.  Would Wednesday 10 June work for you?

**Comment by JoPratt** [comment]
Sure. But too late for 9th June release?

**Comment by JoPratt** [comment]
Spoke to Kat today about India and Singapore content. These are actually Ltd companies, not foundations, so problematic to include them on this page. We decided for now to include some info about their legal status on the Contact us page (as per Amsterdam office listing) and not to add them to the Foundations page for now. Kat is confirming this with Peter on Monday morning.

**Comment by Lynngre** [comment]
@gabemart  please update  "Our organisations" to replace "Our foundations" on the drop down menu
