### ISSUE TITLE
Security policy link

### ISSUE THREAD

**Issue by Anna-Marthe** [akvo/akvo-web#560]
![image](https://cloud.githubusercontent.com/assets/5310896/6682584/d3efefde-ccb5-11e4-99e3-b4dc0f10e998.png)
The link to the security policy document on http://akvo.org/help/akvo-policies-and-terms-2/ is missing

**Comment by Lynngre** [comment]
@gabemart or @loicsans can we just add an additional page ourselves for this or do you need to create a 'security policy' page for us to load the content onto?

@JoPratt  comms to obtain content.

**Comment by JoPratt** [comment]
Security policy is a 24 page pdf. I plan to add only sections 1 & 2 (intro and overarching security policy) to the page as text. Then include a link to the full pdf.

**Comment by JoPratt** [comment]
Due to quantity of editing required, this won't make 9th April release, but will be added to 28th April. 
Now not going to include a link to the full 25 pg PDF as it would need editing before it was OK to go online, and that would take too long.

**Comment by JoPratt** [comment]
I've created a draft page in akvo.org which I'm working on.

**Comment by Lynngre** [comment]
@JoPratt will this still make it in for Tuesday?

**Comment by JoPratt** [comment]
Yes the draft page in akvo.org is ready for publication now. Do I just hit 'publish' and then add the link to the Internal policies section, or is it more complicated than that?

**Comment by gabemart** [comment]
@JoPratt - am I correct in thinking this doesn't need any changes any templates, it's just a change in the content?

**Comment by JoPratt** [comment]
It's a new page I've created in the same format (using the same code phrasing) as the other policy pages. So yes, I think you're correct.

**Comment by Lynngre** [comment]
@jo are you clear re what needs to be done?  Can I close this?

**Comment by JoPratt** [comment]
fixed and closed
