### ISSUE TITLE
Upgrade to SSL

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#562]
upgrade site to 'https:/akvo.org' using the wildcard *.akvo.org SSL cert available.

**Comment by orifito** [comment]
Need to add SSL to analytics before going ahead with the homepage:
```
GET https://analytics.akvo.org/piwik.js net::ERR_CONNECTION_REFUSED
```
We also found some resources embedded in HTTP:
* Videos from vimeo
* http://fonts.googleapis.com/css?family=Quando
* http://fonts.googleapis.com/css?family=Source+Code+Pro:400,900,700,600,300,200,500|Questrial|Inconsolata|Muli:400,300italic,400italic,300|Raleway:400,900,800,700,600,500,100,200,300|Lobster|Lobster+Two:400,400italic,700,700italic|Lato:400,100,300,700,900,100italic,300italic,400italic,900italic,700italic

**Comment by gabemart** [comment]
There are also a number of templates that have hardcoded links to images served over http. I will have to go through and manually change each template.

**Comment by Lynngre** [comment]
I've also found many other areas SSL will cause issues - no rush.  I doubt we can do it next week.  I need to make a list of everything so we can figure out how to fix what will need updating.  I'll also run a check on the templates & include them.  @orifito let's catch up on this next week.

**Comment by Lynngre** [comment]
Dependency is RSR upgrading to https.

How do we deal with users adding insecure content via links etc?
