### ISSUE TITLE
Akvopedia page - add 6th portal

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#569]
Once the food security portal goes live we need to add an extra portal to the page. See also issue #517

I've finished the icon already, so let me know once you need it.

**Comment by Lindaleunissen** [comment]
Just checked with Winona. We can expect the food security portal to be online on the 16th of April.

**Comment by Lynngre** [comment]
@Lindaleunissen is this ready for Tuesday?

**Comment by Lindaleunissen** [comment]
I have an image, not sure if code is ready for 6th portal. @gabemart, is this ready to go?
Will also double check with Winona, as I don't see the portal on Akvopedia at the moment.

**Comment by Lynngre** [comment]
According to Winona delayed until Mid-May

**Comment by gabemart** [comment]
It's ready to go on my end whenever the content is ready.
