### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-web#585]
At http://akvo.org/help/help-support/rsr-help/ some links are broken: 
the links 'register here' and 'reset your username and password' in the foldout of the first question is broken:

http://rsr.akvo.org/accounts/register1/
http://rsr.akvo.org/accounts/password/reset/

The correct links should be: 
http://rsr.akvo.org/register/
http://rsr.akvo.org/myrsr/password_change/

Furthermore: 
Content of third and fourth foldout need to be updating according to how it works with RSR 3.0. (how do I edit a project, how do I put my project online)

**Comment by Lynngre** [comment]
I guess those are RSRv3 links which changed.  Will check with RSR & list the new ones here for updating.

**Comment by JoPratt** [comment]
I fixed the links.
@lauraroverts is there some existing text for describing the process of editing a project and putting a project online, do you know?

**Comment by lauraroverts** [comment]
@CharlotteSoed has been working on a new manual. I assume we can reuse that text. Charlotte, can you confirm?

**Comment by JoPratt** [comment]
I checked in the manual first, but it doesn't appear to address these two points, it seems to be more for field users.

**Comment by Lynngre** [comment]
@CharlotteSoed could you add a comment here when you have a minute please?

**Comment by lauraroverts** [comment]
I just talked to @CharlotteSoed. Apparently this is something that is not explained in the manual. I think we need to write a help-text for describing the process of editing a project and putting a project online.

**Comment by Lynngre** [comment]
@JoPratt  and @charmermark how do we move forward with this?

**Comment by JoPratt** [comment]
Spoke to Laura today. They are working on the admin area of RSR at the moment. The way projects are added and edited is changing and becoming fully integrated into My RSR. (Currently they're still using pdfs). The changes will happen first release in August. We will update this information then.
