### ISSUE TITLE
Link to help & support 

### ISSUE THREAD

**Issue by lauraroverts** [akvo/akvo-web#586]
Not sure if this is the right repo...

For RSR users it would be very helpful to link to RSR user manuals and the help & support page from My RSR.

**Comment by Lynngre** [comment]
Needs to be done from RSR I think. @kardan @KasperBrandt ?

**Comment by Lynngre** [comment]
@lauraroverts in 'My RSR' the footer has a 'support' link.  @kardan and I agree it's quite hidden.

So that should be changed to be more visible/in a more useful area for a user.  @kardan will create an issue on RSR repo & @loicsans will be assigned.

#586 closed
