### ISSUE TITLE
Map on http://akvo.org/seeithappen/ missing pins

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-web#587]
We had to change how the API worked and limit the number of items that gets returned e.g. enforce stricter pagination (since RSR timed out and died otherwise). 

At the moment max items per request have been set to 10 items (that number was picked when doing CPR on RSR). Once we got things under control a bit more we will probably raise that to something like 30 by default and max 100 per request. 

This means that the client code to renders the map needs to be modified to support multiple requests. I think the part that needs to be updated is https://github.com/akvo/akvo-web/blob/2a2df48f8368b1bcc3b27e7e5c0f1f9e8e741967/code/wp-content/themes/Akvo-responsive/json_data_templates/rsr-project-global-map.template.php - but I'm no WP guru so might be totally wrong.

**Comment by Lynngre** [comment]
@zzgvh could we remove the map for the coming release on Tuesday & only replace it once the JSON plugin has been rebuilt?

**Comment by Lynngre** [comment]
#587 fixed & closed
