### ISSUE TITLE
logo not responsive on tablet

### ISSUE THREAD

**Issue by Anna-Marthe** [akvo/akvo-web#622]
The Akvo logo (top left) is not responsive on my samsung tablet SM-T310 (Android version 4.4.2), using the default web browser - in landscape position.

![see screenshot](https://cloud.githubusercontent.com/assets/5310896/7448133/3265a5dc-f244-11e4-94ed-94aec6f7d9c4.png)

**Comment by Lynngre** [comment]
That's really odd, it hasn't rendered as a logo it's just plain text.

It renders correctly on my Samsung phone as the logo which forwards to the site when clicked.

@gabemart @loicsans any ideas why that logo is rendering as 'text'?

**Comment by gabemart** [comment]
That is odd - the entire top banner appears not to have rendered, with the exception of the logo text. Very puzzling. I will look into it.

**Comment by loicsans** [comment]
Can you still this @Lynngre ?

**Comment by Lynngre** [comment]
I couldn't on mine either, will check with @Anna-Marthe

**Comment by Anna-Marthe** [comment]
I checked again - and I get the same result. The issue only arrises in the default samsung browser, and in landscape position

**Comment by Lynngre** [comment]
@Anna-Marthe would you let us know the device model & os version please?

**Comment by gabemart** [comment]
On Nexus 7 with Android 4.4 the behaviour is different but still incorrect, possibly related - the nav bar covers the text at the top of the page, even when fully scrolled up. Same behaviour on a Galaxy Tab 4 10.1 with Android 4.4

![screenshot from 2015-05-26 16 23 02](https://cloud.githubusercontent.com/assets/2589977/7816034/e562d912-03c3-11e5-80fe-5af6fbdcccc9.png)

**Comment by Lynngre** [comment]
@gabemart @loicsans there definitely seems to be some issue on Android tablets.  Gabe in your example all the tabs look like pure text too.

How do we go about correcting this or finding the issue?

**Comment by gabemart** [comment]
@Lynngre unfortunately I don't own any of the affected devices (screengrab above is from an emulator).

I will look into whether chrome remote debugging works with Android emulators. If so I will look into this

**Comment by Lynngre** [comment]
Thanks!  You're a star, @gabemart

**Comment by Lynngre** [comment]
#622 closing for now as has not appeared again.
