### ISSUE TITLE
Akvo.org live - diskspace, memory,server monitoring

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#624]
required to ensure the server doesn't encounter issues we are unaware of.

**Comment by Lynngre** [comment]
@orifito any update on this?

**Comment by orifito** [comment]
Yes, disk space was fixed in https://github.com/akvo/akvo-web/issues/623 as well as some cleaning I made into live server.
With regard to memory, we have enough and there is also 4GB of swap space.
And server monitoring can be reached at http://graphite.support.akvo-ops.org/
