### ISSUE TITLE
Homepage rework

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#632]
Include ways to easily incorporate marketing, calls to action, etc onto the homepage includes removing the tag line & including Akvo in a nutshell.

**Comment by Lynngre** [comment]
@loicsans  & @charmermark to discuss ideas around changes outlined earlier today.

**Comment by Lynngre** [comment]
This work will need to be done in stages.  Some of the homepage changes will be made in time for the release on 7 July, but some will need to wait until August/beginning of Sept.

**Comment by Lynngre** [comment]
@loicsans include 'we love open source' banner in new homepage design.

**Comment by Lynngre** [comment]
@Lindaleunissen to provide billboard images & icons by end of Wednesday 12 August to @loicsans 

@Lindaleunissen & @JoPratt to play with dimensions of content in boxes.

**Comment by Lynngre** [comment]
ensure we keep the scrolling  arrows & 4 little buttons 'scroll' options on the carousel.

**Comment by Lindaleunissen** [comment]
Re aspect ratio / dimensions
Based on the current mock-ups the dimensions are:
Top image - 15:7 (1500x700px)
Wide image - 12:5 (600x240px)
Standard image - 8:5 (400x240px)

If @loicsans / @gabemart think it's nicer if the top image is the same aspect ratio as the wide image (so less height) then that is OK too.
