### ISSUE TITLE
Simplify Footer - part of homepage refresh

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#633]
We need to update the footer as it's currently extremely cluttered.

An idea is to group links into a category instead of having each link individually displayed.  @loicsans we also need to think about the 'Let's be friends' area.  Let me know what your gut is telling you.

![screen shot 2015-05-28 at 15 33 38](https://cloud.githubusercontent.com/assets/2675262/7861219/1e1a6dc4-054f-11e5-9c7c-91e081882380.png)

**Comment by Lynngre** [comment]
@loicsans could we get some initial decluttering done for the next release 7 July?

**Comment by loicsans** [comment]
Yes, I think it'll be ready for a change then.
