### ISSUE TITLE
Add product videos to RSR and FLOW product pages

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#635]
We would like to add the new product videos (https://peak.akvo.org/new-akvo-flow-and-rsr-product-animations/ ) to the RSR and FLOW pages in 9th June release. 

Need advice from Loic/Gabe about best place to put them near the top of each page. Options we have discussed are:
- create a button to 'watch video' - appears as a pop up
- embed immediately above horizontal menu bar
- embed under 2nd graphic (on RSR page)

**Comment by gabemart** [comment]
After consulting with @Lindaleunissen and @loicsans we have decided to place the video at the top of both pages, hidden by default, viewable by clicking a text link the opening description. There is also the ability to add a youtube backup link for places where vimeo is blocked, just like with the annual report.

The PR implements the template changes, I will have to manually add the custom fields to akvoDev once the PR is merged
