### ISSUE TITLE
Akvo-IATI page colour update

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#637]
The Akvo-IATI logo is being updated to a yellow version, which means the IATI page needs an update too (http://akvo.org/products/akvo-iati/) 

- The logo on top needs to be replaced by the new logo. (Gabe)
- Background of images needs to be changed to yellow - not sure whether that is just in the image, or if some of the full width backgrounds are coded.

**Comment by Lynngre** [comment]
Images disappear on mobile. Can we have them so they stay visible. They are quite key.
