### ISSUE TITLE
Foundations page - adding people not functioning as it should

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#667]
After release v1.1.15 issues with the Foundations/organisation page:
- you can't make people appear in more than one board
- correlating the Akvo Foundations groups in the Akvo Foundation members pages with the relevant sections in the Our foundations admin page doesn't work.
- people have different job titles in different places - so Kat should be CFO under Akvo Foundation, but Board director under Akvo Kenya Foundation

**Comment by JoPratt** [comment]
Creating more than one 'Akvo Foundation member' entry for individuals solves the issue of having them appear in more than one board and having different job titles for each position. 

To correlate the Akvo Foundations group with the Akvo Foundations member entries: when you add a new Foundation group in the Akvo Foundation member sidebar menu, you have to make sure that the name you choose for the foundation group is exactly the same as the name you give to the "Class" field in the "Section" of the organisation page you want that foundation member to appear.

Foundation groups can also be edited in the sidebar menu.

Fixed and closed.
