### ISSUE TITLE
All products page

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#672]
All products page (New order in three columns) connected to nutshell

**Comment by Lynngre** [comment]
May be a build only in release for 7 July but content will be live later.

**Comment by Lynngre** [comment]
Delayed until 18 August.

**Comment by Lynngre** [comment]
Change to 'All tools' page.
Copy of the homepage but without the carousel.  Header image is fixed/still.

**Comment by Lynngre** [comment]
@Lindaleunissen to provide icons to design team

**Comment by Lynngre** [comment]
Caddisfly to appear with a 'coming soon' banner. @Lindaleunissen

**Comment by Lindaleunissen** [comment]
Icons and images (including caddisfly with banner) are shared in the webdesign dropbox folder.
