### ISSUE TITLE
Update Akvo Delhi map on "Contact Us"

### ISSUE THREAD

**Issue by charmermark** [akvo/akvo-web#677]
Joy has asked if we can change the map at http://akvo.org/contact-info/#DEL to this:

https://www.google.co.in/maps/place/C-19A,+Green+Park+Extension+Marg,+Block+C,+Green+Park+Extension,+Green+Park,+New+Delhi,+Delhi+110016/@28.5603237,77.2021479,17z/data=!3m1!4b1!4m2!3m1!1s0x390ce271133faa01:0x93a676d483652554?hl=en

**Comment by Lynngre** [comment]
@charmermark this can be changed by Comms edit the 'contact info' page.

I've updated it now as per above.
