### ISSUE TITLE
New homepage & All tools page colours

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#701]
Colour numbers for boxes on new homepage & All tools page to be provided by @Lindaleunissen to @loicsans

**Comment by Lindaleunissen** [comment]
Checking with Anke what exact colours should be as currently RGB, PMS and CMYK are all different shades. If necessary I can provide colours now, but the colour codes might change slightly over the next few days.

**Comment by Lindaleunissen** [comment]
Colours are in the Akvo.org web design dropbox folder, and below.  
Capture - orange #DE8929 
Understand - yellow #FFD200
Share - green #74B631

Resources - pink #DB87C9

Akvo light blue #72CDFF
Akvo dark blue #2C2A74
