### ISSUE TITLE
Ability to add HTML links to images on the site - Phase 2/3

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#71]
Add the ability to add html links to images across the site.  
On modern sites users kind of expect to be able to click on visual content to dive deeper/get more info/take action. Much more visually attractive than text links IMHO. If we can add links to up to date content eg blogs we can keep the site vital and up to date easily.

**Comment by Lynngre** [comment]
@JoPratt is this still on the cards?

**Comment by JoPratt** [comment]
It would be good if we could link certain images across the site. We talked with Thomas yesterday about adding layers of info to the product pages, so to be able to click on a diagram to get a deeper explanation is one example where this would be useful. Another example is adding an image of the staff hand book to the "Working at Akvo" page and clicking on the image to access the pdf. Currently we have certain clickable images such as the "What's happening with RSR?" section on the product pages.

**Comment by loicsans** [comment]
@JoPratt, in the first example: "so to be able to click on a diagram to get a deeper explanation is one example where this would be useful": You describe a tooltip, in the other one is just adding an image to a page that link somewhere. These are 2 different things really. And we cannot add html links to all images on the site, some are loaded in from the html template directly, some are loaded from the stylesheet, some are loaded from the wp-admin, some come trhough API's. 
We need more detail to start thinking about a solution.

**Comment by JoPratt** [comment]
Sounds like a case by case thing. So maybe we close this issue and just look at each instance as it arises.
