### ISSUE TITLE
New Akvo Sites logo on product page

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#729]
The golden Akvo Sites logo needs to change to a yellow one. 
http://akvo.org/products/akvo-sites/

I've got the logo ready, just let me know the measurements and I can send it over.
<img width="439" alt="screen shot 2015-08-18 at 17 18 04" src="https://cloud.githubusercontent.com/assets/5338081/9335633/0ca8103c-45cd-11e5-9f04-ce9695489e17.png">

**Comment by gabemart** [comment]
The current logo is this: http://akvo.org/wp-content/themes/Akvo-responsive/images/akvosites/akvosites_logo_gold_400x75px.png

which is 400x75 with a transparent background

**Comment by Lindaleunissen** [comment]
Thanks @gabemart. New logo is attached below (or here on dropbox https://www.dropbox.com/s/hg9mkreu2p702x0/akvosites_logo_yellow_400x75px.png?dl=0)

![akvosites_logo_yellow_400x75px](https://cloud.githubusercontent.com/assets/5338081/9355653/dd4d7aa6-4672-11e5-8adb-789392698289.png)
