### ISSUE TITLE
Hero blog posts - grouping

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#749]
Figure out how to easily group these to avoid having Comms add a link for each on the bottom of each new post, but with future regionalisation in mind/broader aspect.

@loicsans  to consider options here.

**Comment by Lynngre** [comment]
Comms feel it would be good to have a page dedicated to hero shoot blogposts (by category?) then this page could be used as a link at the bottom of each hero shoot blog post.

**Comment by Lynngre** [comment]
@loicsans to look at initial formatting on page added in backend.

**Comment by Lynngre** [comment]
http://www.akvodev.org/heroes/  - fix the layout/formatting to have 3 clickable images across the width of the page, evenly spaced, with the clickable text directly below each relevant image.

**Comment by Lynngre** [comment]
@samvthom16 could you have a look at how we could styles this page better?  http://www.akvodev.org/heroes-series/  like fix the layout/formatting to have 3 clickable images across the width of the page, evenly spaced, with the clickable text directly below each relevant image.

It needs to be something we can copy or release to live akvo.org.

**Comment by samvthom16** [comment]
@Lynngre Made formatting changes to http://www.akvodev.org/heroes-series/ using custom fields

**Comment by Lynngre** [comment]
Thank you!

#749 fixed & closed

**Comment by Lynngre** [comment]
@samvthom16 could you double check the layout here when less than 3 are added.
Right now if there's only 1 it shifts to the middle of the page & if 2 it's unaligned with the first & 2nd in the top row.

Can we set it to keep them aligned in rows of 3?

**Comment by Lynngre** [comment]
#749 fixed & closed
