### ISSUE TITLE
SSL preparation - update http in code to https

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#750]
Code for fonts, etc embedded in the code needs to be updated to use https:// instead of http:// - for example update stylesheet "http://fonts.googleapis.com/css?family=Quando" to    "https://fonts.googleapis.com/css?family=Quando"

**Comment by Lynngre** [comment]
Content, incl. graphics, also needs to be scanned for http links - plugin Velvet Blues Update URLs can be used for this.

**Comment by Lynngre** [comment]
Note:  Wordpress 4.4 update for responsive images causes issues with images being displayed when image/media file url is http. As per https://github.com/akvo/akvo-provisioning/issues/250

**Comment by Lynngre** [comment]
@samvthom16 to look into this & work with @lynngre on moving ahead.
Lynn to load certificate on akvodev after realease on 17 May, we need to fix what breaks.

**Comment by samvthom16** [comment]
After testing on staging, following urls were not working properly - 
1. https://staging1.akvo.org/seeithappen/all-rsr-project-updates/  (Fetch Updates not working)
2. https://staging1.akvo.org/about-us/partners/ (Map not loading). Replace the url with https in the content through the dashboard.
