### ISSUE TITLE
New team members to team page

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#771]
Do we need Christien, Greta & Annabelle added to the teampage?
Also, we should consider adding Paul Burt as he's been with us before.

**Comment by JoPratt** [comment]
Emily has drafted Greta and Annabelle, we just need photos of them which Alvaro is going to take when they're next in the office (they've not been there much recently). Not sure about Christien. We've been asking Paul for his CV/biog for a while but so far not forthcoming. Emily is also going to do Deepak now.

**Comment by Lynngre** [comment]
Great tx.

**Comment by JoPratt** [comment]
Christien also being actioned by EA/MC

**Comment by earmanetti** [comment]
Annabelle's has been posted to the team page. Christien and Greta's are drafted and queued up in WP. Action now is for Alvaro to photograph them. Still chasing Deepak and Paul.
