### ISSUE TITLE
The Events Calendar plugin - breadcrumb

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#798]
The breadcrumb on the main events page is 'Akvo.org>Blog Archives'.  So the category 'Blog Archives' is being selected by the plugin. It should be just 'Akvo.org' if possible.

Plugin = https://wordpress.org/plugins/the-events-calendar/

![screen shot 2016-01-25 at 13 21 08](https://cloud.githubusercontent.com/assets/2675262/12550843/9502a958-c366-11e5-936c-05d256367ffe.png)

**Comment by samvthom16** [comment]
The breadcrumb on the main events page has been updated to 'Akvo.org>Events'.
