### ISSUE TITLE
Team page limitation

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#802]
Currently, no further team members can be added to the team page as the formatting of the page is completely thrown out if an additional team member is added.

Instead of the team members appearing below their various teams (such as engineering, etc) they are shown as one big list.

Once the additional team member is removed or added to the 'trash' area, the formatting of the page is corrected for visitors once the page is reloaded in the browser.

http://akvo.org/about-us/team/

**Comment by samvthom16** [comment]
The featured image needs to be uploaded with the dimensions 240 x 136.

**Comment by Lynngre** [comment]
This issue has once again raised it's head.

As soon as I remove an additional staff member (Olivia is currently in bin), the problem resolves itself.  

It can't be related to just the image size?  @samvthom16 please have another look.

**Comment by samvthom16** [comment]
The default limit to show the staff in a particular category is 40 which has to be increased to 100.
