### ISSUE TITLE
Events Calendar plugin - individual event page headings

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#805]
Heading and sub heading are too large

**Comment by samvthom16** [comment]
The sub heading has been replaced to h3 from h2

**Comment by Lynngre** [comment]
@samvthom16 could you double check this as the main heading still looks the same size to me, although subheading is smaller.

**Comment by samvthom16** [comment]
So the main heading is using the H1 tag whose font-size is 2.9em. Do you want it to be H2 tag whose font-size is 2.3em?
