### ISSUE TITLE
New RSR product page issue: tabs

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#820]
No spacing between the tabs and image

**Comment by Lindaleunissen** [comment]
Also no spacing between separate tabs. Instead make the buttons a bit wider, so there is more space around the words on it. (see attached wireframe image)

For the text please use same size and fonts as buttons (issue #839)

Change colour of the tabs to # 72CDFF

<img width="832" alt="screen shot 2016-03-09 at 16 12 53" src="https://cloud.githubusercontent.com/assets/5338081/13641904/3da92e38-e612-11e5-8cc1-61c61b831539.png">
