### ISSUE TITLE
New RSR product page issue: carousel text

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#822]
Reduce width of text box on carousel images

**Comment by Lindaleunissen** [comment]
I've done a quick mock up for you, hope this helps. 
The text will never be longer then it is currently on the first slide, so you can use that as a guideline. 

<img width="707" alt="screen shot 2016-03-10 at 14 53 25" src="https://cloud.githubusercontent.com/assets/5338081/13673219/fc9fc5f0-e6cf-11e5-95ba-64f95ab61551.png">

**Comment by Lynngre** [comment]
@samvthom16
