### ISSUE TITLE
New RSR product page issue: overview & features tabs columns

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#823]
Reduce width of text columns for communicate - report - monitor and testimonials to increase space between columns. C-R-M columns and testimonial columns should be same width and spacing

**Comment by Lindaleunissen** [comment]
On the features tab, please slightly increase spacing between C-R-M and the features below. 

And reduce the space between features within a column.

**Comment by samvthom16** [comment]
The spacing between C-R-M and the features below has been increased to 2em. 
The space between the features within a column has been decreased to 2em.

**Comment by Lindaleunissen** [comment]
The spacing between C-R-M and the features below is perfect. Thank you. 

It seems the spacing between features within a column could be decreased a bit more, but could you first adjust the column width? That might solve the problem already. Please refer to the attached mock up to get a better idea of how wide the columns should be. 
<img width="709" alt="screen shot 2016-03-09 at 13 50 48" src="https://cloud.githubusercontent.com/assets/5338081/13637215/1110b346-e5fe-11e5-889d-8b013a0f8359.png">

**Comment by Lindaleunissen** [comment]
Please make the icons the same colour as the header text: # 2C2A74

**Comment by Lindaleunissen** [comment]
@samvthom16 Could you please reduce the column width on both the overview page and the feature page so there is more white space between the columns? C-R-M columns and testimonials should have the same width, approximately 70% of current width. (see mock up above)

Once that is done, I can review the spacing within a column on the features page.

**Comment by samvthom16** [comment]
Have reduced the overall width. But the features within the columns are loosing their alignment due to variable heights. Any suggestions for that?
One would be to keep a fixed minimum height but that would cause invariable space among the features.

**Comment by Lindaleunissen** [comment]
It looks much better this way, thanks Sam. I think the variable height is okay, happy to leave like this for now.

**Comment by Lynngre** [comment]
#823 Fixed & closed
