### ISSUE TITLE
Carousel images

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#830]
Is it possible to remove the black line to the left of the first carousel slide?

**Comment by JoPratt** [comment]
This black line also appears on the first slide of the akvo.org homepage. Can we remove it from there too?

**Comment by samvthom16** [comment]
@JoPratt could you add a screenshot of what you want removed please?

**Comment by JoPratt** [comment]
Looks like the RSR page one is now no longer an issue since the slide now stretches right to the edge of the screen. Here's a shot of the homepage one:
![screenshot 2016-03-08 09 14 52](https://cloud.githubusercontent.com/assets/4302250/13597147/b503af4e-e50e-11e5-923f-95b445605b7b.png)
