### ISSUE TITLE
Akvopedia page: remove menu bar

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#831]
@JoPratt could you elaborate or add a screenshot of what you want removed please?

**Comment by Lindaleunissen** [comment]
This pink menu/navigation bar is the one that should be removed. 

<img width="1407" alt="screen shot 2016-03-10 at 12 40 47" src="https://cloud.githubusercontent.com/assets/5338081/13669741/56bbad6e-e6bd-11e5-9fc2-d401a60308c7.png">

**Comment by Lynngre** [comment]
#831 fixed & closed
