### ISSUE TITLE
New RSR product page: button size and font

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#839]
Could you please increase the size of the buttons? 
The buttons should be a little bit bigger, though the font doesn't have to increase in size. Please change the font to Questrial.

**Comment by Lindaleunissen** [comment]
It would be great if we could change the text on the button and change the page it links to ourselves.

**Comment by Lindaleunissen** [comment]
Regarding the first comment above: please make buttons a bit wider, they don't have to be any higher. Also please round the corners a bit more. Font an stay as it is, as that's the same as elsewhere on the site.
<img width="586" alt="screen shot 2016-03-09 at 16 09 24" src="https://cloud.githubusercontent.com/assets/5338081/13641720/75d71082-e611-11e5-9737-11003e4944f3.png">

**Comment by samvthom16** [comment]
Are we using the font Questrial anywhere else on the website? Needed a reference.

**Comment by Lindaleunissen** [comment]
Can you please make the buttons a bit wider still, so the text has a bit more 'air' around it? 
Also please change the text colour of the buttons to white # ffffff

**Comment by Lynngre** [comment]
@Lindaleunissen @samvthom16 the 'get in touch' button - shouldn't that look like the 'READ MORE' button shown in this issue?

**Comment by Lindaleunissen** [comment]
No, I like it as it is currently, so let's keep it in light blue and Questrial.

**Comment by Lynngre** [comment]
Great thanks for confirmation.  Closing this.
