### ISSUE TITLE
New RSR product page: project and partner ticker

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#840]
Is it possible to have the ticker start at 0 and turn over to the current number? The movement will imply that the number is up to date.

**Comment by Lindaleunissen** [comment]
Would it also be possible to make the headings for the tickers editable in the backend? And link them through to a page?

**Comment by Lynngre** [comment]
@samvthom16 would the original request here re the ticker counting down be possible?  We also need to consider two things.  
- For someone who loads the page again within the same visit it's not really necessary to count down again.  So am assuming looking at cookies would be required.
- The counter should only start ticking down once some has scrolled down the screen to the ticker.  Not sure how that can be judged ie diff screen size.

**Comment by JoPratt** [comment]
@samvthom16 I'm seeing the tickers incorrectly in Chrome v. 49.0.2623.87 even after clearing cache. Looks fine for me in Safari.
![screenshot 2016-03-09 11 11 25](https://cloud.githubusercontent.com/assets/4302250/13702478/dfd4d17e-e786-11e5-8b5c-c7531bc1de7a.png)

**Comment by JoPratt** [comment]
![screenshot 2016-03-11 12 49 41](https://cloud.githubusercontent.com/assets/4302250/13702616/cdb1c2da-e787-11e5-8946-2b03d36e4a77.png)

**Comment by Lynngre** [comment]
#840 fixed and closed.

Moved @JoPratt Chrome problem to another issue https://github.com/akvo/akvo-web/issues/881
