### ISSUE TITLE
New RSR product page: Communicate - Report - Monitor icons

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#841]
The image of the 3 icons on the overview page is currently missing. What is the best way to do this, so the image also works when the text is stacked on a mobile device? 

I could make an image of a blue hexagon, and then the icons could be added on top using the same code as on the features page? In that case - should the connecting dotted line be part of the image, or should that be coded? 

If you want me to make 3 graphics with the icon embedded in them, then I can do that too.

**Comment by Lindaleunissen** [comment]
Same goes for this image on the features page. I can embed it into the header image, but not sure that would work well if text blocks are stacked on mobile devices.

**Comment by samvthom16** [comment]
On the overview page, I think we should have 3 individual graphics for the icons. But I'm not sure if the lines would be connected as there is some margin between the columns. Although it would look fine on small screen devices. 

For the features page lets first try by embedding it into the header image. Lets see how that works on the small screen devices.

**Comment by Lindaleunissen** [comment]
I've got the images ready, just nowhere to upload them in the backend of the overview page yet. (they're attached)

I've embedded C-R-M icons in the header image for the features page, but at the moment that doesn't work well on smaller screens and mobile devices. 

![communicate_icon](https://cloud.githubusercontent.com/assets/5338081/13643646/c67fb946-e619-11e5-83d5-0985414b7777.jpg)
![monitor_icon](https://cloud.githubusercontent.com/assets/5338081/13643647/c69af558-e619-11e5-9bf7-56470cbea21a.jpg)
![report_icon](https://cloud.githubusercontent.com/assets/5338081/13643648/c6a03e00-e619-11e5-9ed0-d2c46197e07f.jpg)

**Comment by Lindaleunissen** [comment]
Regarding the features page; can you add the icons underneath the header image, basically the same as on the overview page?

**Comment by Lynngre** [comment]
@samvthom16 can you please check the icons on a mobile device on features tab.  It's not working check @Lindaleunissen 's comment above.

**Comment by Lynngre** [comment]
#841 fixed & closed
