### ISSUE TITLE
New RSR product page: support page lay-out

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#843]
Please make the blue rectangles less wide. The white space left and right of the rectangles should be visible even if window isn't full screen on a lap-top. 

Descriptive text should be less wide. - similar to other pages once they are updated. 

Is it possible to make the screen grab image (about IATI) overlap the edges of the blue rectangle - like you did with the testimonial?

**Comment by samvthom16** [comment]
Right now the descriptive text takes 48% of the container's width. How much less wide should it be?

The screen grab image overlapping to one side of the edge is possible. It breaks for different screen sizes.

**Comment by Lindaleunissen** [comment]
I recon the blue boxes should be around 40% less wide then they are currently. Once that is adjusted the 48% of the container width is probably fine.

**Comment by Lynngre** [comment]
@samvthom16
