### ISSUE TITLE
New RSR product page: light blue colour

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#845]
All the light blue on the page - text, buttons, tabs, rectangles on the support tab should have the colour Akvo light blue: # 72CDFF

Related to #820 #839 #825

**Comment by Lindaleunissen** [comment]
Sorry - I was a bit unclear about the colour of the boxes on the support tab. They should be lighter shade of # 72CDFF
@loicsans what percentage of the colour do you usually use? 30%?

**Comment by Lindaleunissen** [comment]
Confirmed by @loicsans. It should indeed be set to a transparency of 30%

**Comment by Lynngre** [comment]
@samvthom16
