### ISSUE TITLE
New RSR product page: add links to API section on Support tab

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#846]
Please can you add a link to the API image and enable us to add a link in the text

**Comment by samvthom16** [comment]
Link to the image and text are different or will remain the same?

**Comment by samvthom16** [comment]
Or should I just wrap the whole blues section in a link?

**Comment by Lynngre** [comment]
@samvthom16 re the 'link in text'.  Just update the 'description' box to be the same as the 'image text' boxes where the user has the ability to format text/use html if they want to.  Right now a url cannot be added as it's a pure text field.
