### ISSUE TITLE
New RSR product page: add anchors to Akvo RSR tour section

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#858]
We need to link to the 'Akvo RSR tour' from the Take the tour button. Please can you add an anchor to the start of the tour.

We also need to link to the IATI part of the tour (2nd tour element) from the IATI (2nd) carousel slide. Please can you add an anchor to this section of the tour. 

(It might be a good idea to add anchors to all 3 elements, although currently we only need to link to the start of the tour and the 2nd element.)

**Comment by Lynngre** [comment]
#858 fixed
