### ISSUE TITLE
New RSR product page: Spacing

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#860]
On the overview page:
- [x] Please reduce spacing between the carousel and the C-R-M icons.
- [x] Reduce the spacing between video button and video
- [ ] Reduce the spacing between the testimonials and the tickers.
- [ ] Reduce the spacing between the tickers and the contact button.

On the support page:
- [ ] Please reduce the spacing between the bottom blue box and the help center button

**Comment by Lindaleunissen** [comment]
In addition to the above:
Please move the video and tour button slightly up, so the spacing between C-R-M and the buttons is reduced, and the spacing between the buttons and the testimonials is increased.

**Comment by Lindaleunissen** [comment]
This needs a bit more tweaking:

On the overview page:
- [ ] Reduce the space between the carousel and CRM icons by 1em
- [ ] Increase the space between the video/at a glance button and the testimonials by 2 em
- [ ] Decrease the space between testimonials and ticker headers by 1em
- [ ] Decrease the space between tickers and contact button by 1em

Ignore the support page for now - I'm designing a new mock up for that.

**Comment by Lynngre** [comment]
@samvthom16 would you check this please?

**Comment by samvthom16** [comment]
The spacing between the carousel and CRM icons comes from the icons itself.

**Comment by Lindaleunissen** [comment]
Apologies, I didn't realise. I'll adjust the CRM images. Thanks!

**Comment by Lindaleunissen** [comment]
@samvthom16 I removed the white space around the CRM icons on Akvo dev. The spacing between the top image and CRM should still be reduced by 1em.

**Comment by samvthom16** [comment]
@Lindaleunissen : Have fixed the images on both overview and features. Please have a look at the spacing and let me know.

**Comment by Lindaleunissen** [comment]
Spacing between carousel and CRM symbols is perfect now thanks. 

Please increase the text between symbols and the titles Communicate, Report, Monitor by 1em.

Please increase the space between the [watch the video] / [take a look] buttons and the testimonials with 2em. 

Please decrease the space between testimonials and tickers by 1em

**Comment by samvthom16** [comment]
@Lindaleunissen 
Have increased the space between symbols and titles by 1em

Have increased the space between [watch the video] and testimonials by 2em

Can't decrease the space between testimonials and tickers as it will affect the overall spacing of the document. This is the minimum space between each element.

**Comment by Lindaleunissen** [comment]
Perfect. Thanks!

**Comment by Lynngre** [comment]
#860 fixed and closed
