### ISSUE TITLE
New RSR product page issue:  Support tab broken image

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#880]
Broken image is displayed on FireFox in the 'Akvo RSR API'.

In the custom field 'support section' there is an option to add an image.  This is being loaded whether or not an image has been saved.

![screen_shot_2016-03-14_at_17_36_26](https://cloud.githubusercontent.com/assets/2675262/13751820/39ab287e-ea0c-11e5-9edf-16bccd38e228.jpg)
![screen shot 2016-03-14 at 17 35 35](https://cloud.githubusercontent.com/assets/2675262/13751824/3ef411ce-ea0c-11e5-989c-651138c9a1bc.png)

Chrome & Safari ignore the missing image.

**Comment by samvthom16** [comment]
The content was not in the right fields. I have fixed it from the back end.

**Comment by Lynngre** [comment]
@samvthom16 great, thanks.

**Comment by Lynngre** [comment]
#880 fixed & closed
