### ISSUE TITLE
RSR page: ticker in Chrome

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#881]
@samvthom16 I'm seeing the tickers incorrectly in Chrome v. 49.0.2623.87 even after clearing cache. Looks fine for me in Safari.

As only @JoPratt seems to be having this issue for now, it's not urgent, although we should get feedback from others, which I'll try to get this week.

![cdb1c2da-e787-11e5-8946-2b03d36e4a77](https://cloud.githubusercontent.com/assets/2675262/13755784/23d06ea4-ea1d-11e5-85ec-f4224fb65443.png)
![dfd4d17e-e786-11e5-8b5c-c7531bc1de7a](https://cloud.githubusercontent.com/assets/2675262/13755785/23d30a92-ea1d-11e5-9951-66db7c93e979.png)

**Comment by samvthom16** [comment]
I had fixed this issue. Is this still happening in chrome v. 49.0.2623.87?

**Comment by Lynngre** [comment]
@samvthom16  it looks like it's actually in all browsers if you are using anything less than 100% zoom level.

![screen shot 2016-03-15 at 09 53 34](https://cloud.githubusercontent.com/assets/2675262/13772362/f7857214-ea93-11e5-8445-f841bd98ae96.png)

**Comment by Lynngre** [comment]
#881 Fixed & closed.
