### ISSUE TITLE
New RSR product pages: make title of Akvo RSR Tour section editable

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#885]
Feedback from Mark TW is that the tour is too insubstantial to be called a tour. (He thinks it should be a lot more substantial and have its own tab but had we discussed this and agreed on max 3 elements to tour and max 4 tabs). Hence I suggest changing the heading of this section to "At a glance". 

It might be better if we can edit it ourselves.

**Comment by Lynngre** [comment]
#885 fixed & closed
