### ISSUE TITLE
Footer: Newsletter sign-up

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#907]
It seems at some stage the  newsletter sign-up has become wider and is being stacked instead of being narrower and displayed on one line as it was previously.

This is how it looked back in January. (Which is what we want).

![screen shot 2016-04-04 at 14 53 07](https://cloud.githubusercontent.com/assets/2675262/14248452/02be45de-fa75-11e5-9785-9c92bb9f015c.png)

Change from this:

![screen shot 2016-04-04 at 14 50 29](https://cloud.githubusercontent.com/assets/2675262/14248476/1e053654-fa75-11e5-9eb3-41429777e819.png)

**Comment by Lynngre** [comment]
@samvthom16 we also need/want a 'reCAPTCHA' to be used before the form is actually 'submitted'.  The Captcha details/signup are under the 'gravity forms' settings area if needed.  Let me know if you need the snippet though.

**Comment by JoPratt** [comment]
Would it be better to replace this sign-up with a button saying 'Newsletters and bulletins' which links to http://akvo.org/newsletters/ as there are currently several newsletter sign up options, and this is likely to increase?

**Comment by Lynngre** [comment]
@JoPratt that sounds great as we're getting so many spam signups for that form on the site.

@samvthom16 please could we remove that whole footer block containing the newsletter sign up.  So we'll have the 'Let's be friends' social media icons directly above the 'product roadmaps' to 'Service status' banner.

**Comment by JoPratt** [comment]
@Lynngre What about the button?

**Comment by Lynngre** [comment]
As discussed adding an icon under 'let's be friends' (typewriter) with hover of 'newsletters & bulletins' to link to http://akvo.org/newsletters/

**Comment by Lynngre** [comment]
#907 fixed & closed
