### ISSUE TITLE
New RSR product page issue:  Get in touch form button

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#908]
As discussed in the post RSR product page release meeting, move the 'get in touch' button from the bottom of the 'overview' tab to the top right of the overall page (keeping option to customise hyperlink/text in admin area). 

Style in the same format as the 'talk to us now' button on http://akvo.org/products/pricing/

**Comment by Lindaleunissen** [comment]
We've changed our mind about this, and would prefer the get in touch button to stay where it is. 

There's a few reasons for this; It makes the page look unbalanced and cluttered, and it isn't in line with Akvo's style of communication as we've been doing in the past. 
@Lynngre @samvthom16

**Comment by samvthom16** [comment]
Can we close this then?

**Comment by Lynngre** [comment]
closing as linked https://github.com/akvo/akvo-web/issues/966
