### ISSUE TITLE
12/4 release: Changes to http://akvo.org/products/pricing/ 

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#910]
Remove the Openaid logo and make sure the other two logos are centred on the page. We also need to change the Akvo Sites logo as it's out of date - so either make the logos editable by comms or replace it for us (Linda to supply correct logo). 

Comms to edit text to reflect existence of new RSR pricing tab. 

Please change the 'Talk to us now' button to 'Get in touch' and change the link to the Contact form. 

(This page will disappear altogether in June release.)

**Comment by samvthom16** [comment]
@JoPratt 
Link of the Get in touch button is editable from the backend.

**Comment by samvthom16** [comment]
@Lindaleunissen 
Please provide the required logos

**Comment by Lindaleunissen** [comment]
![akvo_sites-350px](https://cloud.githubusercontent.com/assets/5338081/14454723/ccac836e-0093-11e6-8fc1-ad81ee89aae7.png)
here you go @samvthom16

**Comment by Lynngre** [comment]
#910 fixed and closed
