### ISSUE TITLE
12/4 release: Move API section

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#911]
Please move the API content from http://akvo.org/products/rsr/#support to the bottom of the features tab http://akvo.org/products/rsr/#features. Please add it as a new section underneath the 'Akvo RSR at a glance' section, without the blue background.

**Comment by Lynngre** [comment]
@JoPratt we also need some link to the API information (ie how to use the API)

**Comment by JoPratt** [comment]
There is a link in the text already

> On 7 Apr 2016, at 13:47, Lynn <notifications@github.com> wrote:
> 
> @JoPratt <https://github.com/JoPratt> we also need some link to the API information (ie how to use the API)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub <https://github.com/akvo/akvo-web/issues/911#issuecomment-206875404>

Jo Pratt
Communications Manager
Akvo

www.akvo.org <http://www.akvo.org/>

Skype: jo10008
Twitter: @jo108

I usually work Monday mornings, Tuesdays, Wednesdays and Fridays.

=====

Latest Akvo Articles

- Why Monitoring & Evaluation? <http://akvo.org/blog/why-monitoring-evaluation/?pk_campaign=M&E&pk_kwd=M&E>
- End-user feedback: who do you call? <http://akvo.org/blog/end-user-feedback-who-do-you-call/?pk_campaign=End%20User&pk_kwd=End%20User>
- Akvo RSR: what’s coming soon <http://akvo.org/blog/akvo-rsr-whats-coming-soon/?pk_campaign=Akvo%20RSR%20what's%20next&pk_kwd=Akvo%20RSR>

=====

**Comment by Lynngre** [comment]
Ok I see that the Swagger list is there too via the SupportHero link. thanks.

**Comment by samvthom16** [comment]
Custom field to be created while going live under the features tab: features_section. 

Remove the content of the API section from the support tab.

**Comment by Lynngre** [comment]
#911 fixed & closed
