### ISSUE TITLE
Blog on home page toggle

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#913]
Please can we have an option to choose whether each blog published should appear on the home page or not - tick box or similar.

**Comment by Lynngre** [comment]
@samvthom16 this could be as easy as using a 'publish to homepage' category?

**Comment by samvthom16** [comment]
There is a problem with using a category as it will be displayed on the breadcrumbs. Is that ok? Or should I be thinking of an alternative?

**Comment by Lynngre** [comment]
We need to think of an alternative.

**Comment by Lynngre** [comment]
@samvthom16 to create same setup as the two boxes to the right of the latest RSR project update.

**Comment by Lynngre** [comment]
#913 fixed & closed. Option to select sticky post for homepage widget added.

![screen shot 2016-05-10 at 12 11 24](https://cloud.githubusercontent.com/assets/2675262/15143403/cb3ae15c-16a9-11e6-9987-9f833c3203b7.png)

**Comment by Lynngre** [comment]
@samvthom16 the 'Latest blog' title on the homepage blogpost widget is not being updated by the custom field in the backend.  Would you add a fix for that please?

![screen shot 2016-05-10 at 13 18 33](https://cloud.githubusercontent.com/assets/2675262/15144821/1afbd040-16b2-11e6-8960-115836fe2086.png)
![screen shot 2016-05-10 at 13 20 14](https://cloud.githubusercontent.com/assets/2675262/15144822/1b11caee-16b2-11e6-9d77-02133be37623.png)

**Comment by Lynngre** [comment]
@samvthom16 please fix 'small item 1 title' issue for Tuesday's release.

**Comment by samvthom16** [comment]
Custom field to be added with the slug - si_item_title_1
