### ISSUE TITLE
RSR product page: text width

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#942]
Text is much wider on RSR page then in original mock up. This is especially obvious on the pricing page. Can we reduce the width of text to more resemble the mock up?

**Comment by samvthom16** [comment]
The text width is similar to the width at akvo dash. Reducing this width will overall decrease the width of the container.

**Comment by Lindaleunissen** [comment]
I'd like the ratio between images, text and buttons to be more like on the mock up. If that means reducing the width of the container then fine. We'd have to upload the pricing image separately though, so it's not in the container and is slightly wider then the text.

**Comment by Lynngre** [comment]
@samvthom16 for next release please

**Comment by Lynngre** [comment]
@Lindaleunissen please confirm this is ok on akvodev

**Comment by Lindaleunissen** [comment]
Still looks the same to me. The pricing image is still part of the container. So the image is still less wide then the text.

**Comment by Lindaleunissen** [comment]
It looks better, but this issue goes further then the pricing page. If I put the mock up and the actual page along side each other, the lay-out is not the same. It's mainly little things, spacing, button size, etc, but it contributes to the look and feel of the page, which isn't the same in the mock up and the actual page. Please see examples below. Mock ups on the left, actual page on the right. Changes have been made in the content since the mock ups were produced, so it's not a 1 to 1 comparison, but hopefully it still shows what I mean.


<img width="920" alt="screen shot 2016-05-17 at 10 54 00" src="https://cloud.githubusercontent.com/assets/5338081/15318612/c16b4f02-1c1e-11e6-8066-cdd29542e676.png">
<img width="1019" alt="screen shot 2016-05-17 at 11 01 00" src="https://cloud.githubusercontent.com/assets/5338081/15318616/c3dc9052-1c1e-11e6-8390-840507b97e0c.png">

**Comment by Lynngre** [comment]
WIll move these further issues to a new issue for next release.
#942 closed
