### ISSUE TITLE
Menu - subitems

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#943]
@samvthom16 is it the CSS which changes the menu behaviour in WordPress for subitems?
When I add a submenu item, it doesn't move out the items neatly to the right as usual.

![screen shot 2016-04-12 at 21 10 35](https://cloud.githubusercontent.com/assets/2675262/14472373/33098d28-00f3-11e6-9fe5-ab16eb638837.png)
![screen shot 2016-04-12 at 21 10 13](https://cloud.githubusercontent.com/assets/2675262/14472380/37bfe272-00f3-11e6-97e9-983ee17ebfdd.png)

**Comment by samvthom16** [comment]
The menu items can only have a depth level of 1 sub menu. The new sub menu items are breaking as they are 2 levels deeper in the menu.

**Comment by Lynngre** [comment]
@samvthom16 this is possible in WordPress, but is it the theme which restricts it?
Is there a way around that?

**Comment by samvthom16** [comment]
The theme restricts this. We will have to rework the menus to incorporate this.

**Comment by Lynngre** [comment]
#943 fixed & closed
