### ISSUE TITLE
Dash R&D page: overlay image

### ISSUE THREAD

**Issue by Lindaleunissen** [akvo/akvo-web#948]
I've tried to overlay a graphic on the second image, but it get's restricted to the text width. Could you set it so it gets displayed in it's full size?

**Comment by samvthom16** [comment]
Is the purpose overlay or to display the complete image before the title?

**Comment by Lindaleunissen** [comment]
It should look like this. The photo may be cut of at the side when looking on mobile devices, but the transparent image with the blocks should be visible at all times. 

[how dash works v2.pdf](https://github.com/akvo/akvo-web/files/220647/how.dash.works.v2.pdf)

**Comment by samvthom16** [comment]
Please send me the overlay image separately

**Comment by Lynngre** [comment]
#948 fixed & closed
