### ISSUE TITLE
New RSR product page: flickering when moving between tabs

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#951]
Find a way to smooth the transition from one #TAB to the next.  Right now there's an obvious flickering when the page 'realigns' to the correct anchor.

@samvthom16 is there any way to improve on this?

**Comment by Lynngre** [comment]
@samvthom16 any news on this?

**Comment by Lynngre** [comment]
@Lindaleunissen would you check this.  I had a look and it seems better for me.

**Comment by Lindaleunissen** [comment]
Looks great. Thank you!
