### ISSUE TITLE
Caddisfly R&D page

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#954]
Release by 17 May

**Comment by Lynngre** [comment]
Comms are working on this layout currently, similar to DASH page layout.

**Comment by Lynngre** [comment]
@samvthom16 Caddisfly page to be done for Tuesday's release as per wireframe.

https://www.dropbox.com/s/w39zhhiabi84uvq/Caddisfly%20page%20mockup%2010-05-2016.pdf?dl=0

**Comment by samvthom16** [comment]
Find the caddisfly page layout here http://www.akvodev.org/akvo-caddisfly/

**Comment by Lynngre** [comment]
@JoPratt & @Lindaleunissen please confirm ok

**Comment by Lindaleunissen** [comment]
The images all have different heights, though they shouldn't. The top image with the overlaid text is fine, the other images should all be the same height, shallower then the top image (like the 2nd image on the page). 

The icon's in the "What tests will Caddisfly perform at launch" are currently set to be font awesome icons. They are however icons designed by me, so I will need to upload images in stead of a line of code.

**Comment by samvthom16** [comment]
Other images except the 3rd one is taking the shallow size. Size of the 3rd image is dependant on the overlay image.
