### ISSUE TITLE
Product/R&D page logos

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#955]
Product logo at the top of each product/R&D page should be customisable by comms team.

**Comment by Lynngre** [comment]
@samvthom16 would it be possible to make this change for all the product pages too?

**Comment by Lynngre** [comment]
Added for Dash R&D page to release v1.2.5 Wongi waverider.

Rest will be updated for following release.

**Comment by Lynngre** [comment]
@samvthom16 can you ensure this is done for all product pages/tool pages in time for Tuesday's release.

**Comment by samvthom16** [comment]
Custom Field with the slug - 'logo' to be added for caddisfly, rss, flow and sites pages
