### ISSUE TITLE
Product landing page

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#956]
Changes:
Remove wood shaver image & replace with product image - to be rotated.
Remove Akvopedia as this now falls under 'resources'.
Remove additional box next to Akvopedia as products will all move one box up.

**Comment by Lynngre** [comment]
@Lindaleunissen when could the landing page be updated?

**Comment by Lindaleunissen** [comment]
Done!

**Comment by Lynngre** [comment]
Nice, thanks!
