### ISSUE TITLE
Annual reports page

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#967]
The annual reports page http://akvo.org/about-us/annual-reports/ needs some tweaking:

The menu bar formatting has gone awry as it's now too long. I think we can remove the bar altogether. If that's not going to work, can we remove the words "Annual report" and just leave the year for each item.

We can't currently edit the text descriptors under each item and the one for 2014 doesn't make sense as it's an online report. Please can you make these text sections editable. 

Also please make the headings of each item editable. We would like to remove the full stops and change the case to sentence case instead of initial caps. Also, for 2015, we currently don't have an annual report,  only an accounts report, so we need to reflect that in the heading.

**Comment by samvthom16** [comment]
We no longer use this page
