### ISSUE TITLE
Lumen (Dash) R&D page

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#970]
Please can you add a link field to the text box in the top image on the Lumen R&D page http://akvo.org/akvo-lumen/. Currently there is no way to add a link in admin, although the box appears as hyperlinked in the front end. 

Ideally this really needs to be fixed by 13.00 AMS time on 11 May.

**Comment by samvthom16** [comment]
Fixed. Can add the links through the admin.

**Comment by JoPratt** [comment]
I think you might have linked the wrong image. We don't need a link on the diagram, but on the top image i.e. the one that is the same place as the carousel on the RSR pages. The text box overlaying the photo needs to be linkable. Please can you add a link there and remove the one from the diagram. Thanks!

**Comment by samvthom16** [comment]
All the images including the top image are linkable. For the time being I have linked the text on the top image to google.

**Comment by JoPratt** [comment]
this is now fixed, thanks

**Comment by JoPratt** [comment]
Please can you remove the link on the diagram. Now appears in front end that this graphic is clickable when it shouldn't be.

**Comment by Lynngre** [comment]
#970 fixed & closed
